server:
  port: 1001
  servlet:
    context-path: /poi

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    username: demo
    password: demo
    url: jdbc:dm://ip:port
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
